let poem = '';

let grammar = tracery.createGrammar({
"origin":["A HOUSE OF #material#\n#place#\nUSING #light_source#\nINHABITED BY #inhabitants#"],
"material":["SORROW", "DOOM", "LOVE", "PAIN", "TREACHERY", "RAGE", "GLOOM", "JOY", "CONFUSION", "LUST", "HAPPINESS", "DESPAIR", "PARANOIA", "BROKEN DREAMS", "RELIEF", "HOPE", "REVENGE"],
"place":["IN A BETTER TIME", "MAD HOUSE", "IN A RUT", "BY THE LORD", "BY AN ABANDONED KIN", "IN A DARK PLACE", "IN A DESERTED IDEA", "IN DENSE THOUGHT", "IN THE END", "AMONG THE OTHERS", 
"IN THE DARKNESS", "AMONG THE DEPTHS", "ON A ROLL", "ON STABLE GROUND", "IN A FIERY, HOT PLACE", "IN A PLACE THAT IS SURROUNDED BY DEATH", "IN A DESERTED PLAIN", "IN AN UNKOWN CLIMATE",
"INSIDE A GLACIER", "ON THE WAY", "IN THAT PLACE", "IN THE WEBS", "BY THE SKIN OF ITS TEETH", "AMONG OTHER OTHERS", "IN A TERRIBLE PLACE", "IN A DAZE", "AMOUNG THE STARS"],
"light_source":["WARMTH", "LIGHT", "THAT FUZZY FEELING", "SPIRIT'S BURN"],
"inhabitants":["PEOPLE WHO HAVE LITTLE", "PANHANDLERS", "BIRDS AND BEES", "PEOPLE UNDER THE SPELL", "EVERY BEING SUCCUMBING TO THE EVENTUAL TICK OF TIME", 
"OLD SOULS", "THE CREATURES THAT SURROUND US", "MARIONETTES", "NUCLEAR FAMILIES", "THE GLUTTONY THAT WAS FORWORNED", "COLLECTORS OF PAIN", "ENEMIES AND LOVERS", "PEOPLE WHO YEARN FOR THE VOID", 
"VERY WEAK PEOPLE", "AMERICAN IDIOTS", "LITTLE MEN", "PEOPLE FROM THE ENEMY", "OUR REFLECTION", "EGO", "THOSE WHO SPEAK BUT NONE CAN UNDERSTAND", "HUNTERS AND GATHERERS", "PEOPLE WHO LOVE TO HATE"],



});

function setup() {
  createCanvas(1920, 1080);
  noLoop();
}

function draw() {
  background(220);
  let y = 70;
  let lineHeight = 110;
  textSize(15);
  for (let i = 0; i < 9; i++) {
  poem = grammar.flatten("#origin#");
text(poem, 70, y);
y += lineHeight; 
}}